#!/usr/bin/env bash

# Read the file /etc/passwd line by line using a while loop and IFS
while IFS=: read -r username password user_id group_id home_directory command
do
    # Get the group name using the group_id
    group_name=$(getent group "$group_id" | cut -d: -f1)

    # Display the user information
    echo "The user $username is part of the $group_name gang, lives in $home_directory and rides $command."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_id INFO"
    echo
done < /etc/passwd

~
~
~
~
~
~
