#!/usr/bin/env bash
# Using a while loop with an if statement to display "Best School" 10 times
counter=0
while [ $counter -lt 10 ];
 do
    if [ $counter -eq 8 ];
 then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
