#!/usr/bin/env bash
# Using a while loop with a case statement
counter=1
while [ $counter -le 20 ];
do
    case $counter in
        4)
            echo "$counter and bad luck from China"
            ;;
        9)
            echo "$counter and bad luck from Japan"
            ;;
        17)
            echo "$counter and bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done

