#!/usr/bin/env bash
# Using a while loop to display time for 12 hours and 59 minutes

current_hour=0

while [ $current_hour -le 12 ]; do
  minute=1
  while [ $minute -le 59 ]; do
    echo "Hour: $current_hour $minute"
    let "minute++"
  done
  let "current_hour++"
done
