#!/usr/bin/env bash
# Displays content of current directory

for file in *-* .[!.]* ..?*
do
  # Skip hidden files
  if [[ $file == .[!.]?* ]]
  then
    continue
  fi
  # Display the filename starting from the second dash
  echo -n "${file#*-} "
done
echo
